name: Automation Script

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Initiating
        uses: actions/checkout@v2.3.4
      - name: Installing Java Development Kit
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Building APK
        run: |
          /bin/bash ./gradlew assemble --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: APK
          path: fall-detector/build/outputs/apk/release/fall-detector-release-unsigned.apk
